### ISSUE TITLE
Port from Python 2 to Python 3

### ISSUE THREAD

**Issue by Qarj** [Qarj/bitmeter-desktop#2]
Will need to address saving preferences on exit

```
Traceback (most recent call last):
  File "./main.py", line 175, in OnClose
    self.prefs.Save()
  File "/home/tim/git/bitmeter-desktop/prefs.py", line 19, in Save
    self.db.SavePrefs(self.prefs)
  File "/home/tim/git/bitmeter-desktop/db.py", line 47, in SavePrefs
    for k, v in vals.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by Qarj** [comment]
It is just `items` in Python 3
